#build_mau:
#  outputs:
#    dev:
#      account: sfedu02-lvb17920
#      database: USER_DB_BULLFROG
#      password: Generative121@
#      role: TRAINING_ROLE
#      schema: analytics
#     threads: 1
#      type: snowflake
#      user: BULLFROG
#      warehouse: BULLFROG_QUERY_WH
#  target: dev
stock_analytics:
  outputs:
    dev:
      account: sfedu02-lvb17920
      database: USER_DB_BULLFROG
      password: Generative121@
      role: TRAINING_ROLE
      schema: analytics
      threads: 1
      type: snowflake
      user: BULLFROG
      warehouse: BULLFROG_QUERY_WH
  target: dev
